# 本番環境用のdocker-compose
version: "3"
services:
  nginx:
    build:
      # dockerfileは、親ディレクトリをCOPYできないので、
      # ここで、contextをルートに設定している。
      context: ./
      dockerfile: ./front/Dockerfile.prod
    container_name: nginx-container
    ports:
      - "80:80"
    tty: true
  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile.prod
#    command: # 解凍したファイルを実行する ex) /root/bin/hello -Dplay.http.secret.key=xxxxxxxxxxxx
#    expose:
#      - "9000"