# ビルド環境
FROM node:12.4.0-alpine AS build-stage
WORKDIR /app
COPY ./front /app/
RUN npm init -y
RUN npm install
RUN npm run build

# 本番環境
FROM nginx:1.13.12 as production-stage
COPY --from=build-stage /app/public/bundle /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

